#!/bin/bash
# ╔══════════════════════════════════════════════════════════════════╗
# ║                    MahsaBot Installer v1.0                        ║
# ║          Telegram VPN Subscription Management Bot               ║
# ║                   github.com/benAliAlizadeh/mahsabot                    ║
# ╚══════════════════════════════════════════════════════════════════╝

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'
BOLD='\033[1m'

INSTALL_DIR="/var/www/mahsabot"
DB_NAME="mahsabot_db"
DB_USER="mahsabot_user"

print_banner() {
    clear
    echo -e "${CYAN}"
    echo "  ╔══════════════════════════════════════╗"
    echo "  ║         🤖 MahsaBot Installer          ║"
    echo "  ║     VPN Subscription Bot v1.0        ║"
    echo "  ╚══════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
}

log_info()  { echo -e "${GREEN}[✓]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
log_error() { echo -e "${RED}[✗]${NC} $1"; }
log_step()  { echo -e "\n${BLUE}${BOLD}━━━ $1 ━━━${NC}\n"; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "این اسکریپت باید با دسترسی root اجرا شود"
        echo "sudo bash mahsabot.sh"
        exit 1
    fi
}

check_os() {
    if ! grep -qi 'ubuntu\|debian' /etc/os-release 2>/dev/null; then
        log_warn "این اسکریپت برای Ubuntu/Debian بهینه شده. ممکن است روی توزیع‌های دیگر مشکل داشته باشد."
    fi
}

install_dependencies() {
    log_step "نصب پیش‌نیازها"
    
    apt-get update -y > /dev/null 2>&1
    log_info "لیست پکیج‌ها بروزرسانی شد"
    
    apt-get install -y apache2 mysql-server php php-mysql php-curl php-xml php-soap php-gd php-mbstring php-gmp php-bcmath unzip curl git certbot python3-certbot-apache > /dev/null 2>&1
    log_info "Apache, MySQL, PHP و ماژول‌ها نصب شد"
    
    systemctl enable apache2 mysql
    systemctl start apache2 mysql
    log_info "سرویس‌ها فعال شدند"
}

setup_database() {
    log_step "پیکربندی دیتابیس"
    
    echo -e "${CYAN}رمز عبور دیتابیس${NC} (برای کاربر $DB_USER):"
    read -s DB_PASS
    echo ""
    
    if [[ -z "$DB_PASS" ]]; then
        DB_PASS=$(openssl rand -base64 16 | tr -d '=/+')
        log_info "رمز عبور تصادفی ایجاد شد: ${YELLOW}${DB_PASS}${NC}"
        log_warn "این رمز را ذخیره کنید!"
    fi
    
    mysql -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
    mysql -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';"
    mysql -e "GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';"
    mysql -e "FLUSH PRIVILEGES;"
    
    log_info "دیتابیس ${DB_NAME} و کاربر ${DB_USER} ایجاد شد"
}

download_bot() {
    log_step "دانلود فایل‌های ربات"
    
    if [[ -d "$INSTALL_DIR" ]]; then
        log_warn "مسیر ${INSTALL_DIR} از قبل وجود دارد"
        echo -e "آیا می‌خواهید بازنویسی شود؟ (y/N)"
        read -r confirm
        if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
            log_error "نصب لغو شد"
            exit 1
        fi
        rm -rf "$INSTALL_DIR"
    fi
    
    git clone https://github.com/benAliAlizadeh/mahsabot.git "$INSTALL_DIR" 2>/dev/null || {
        mkdir -p "$INSTALL_DIR"
        log_warn "کلون از گیت ناموفق. فایل‌ها به صورت دستی کپی شوند."
    }
    
    chown -R www-data:www-data "$INSTALL_DIR"
    chmod -R 755 "$INSTALL_DIR"
    log_info "فایل‌ها در ${INSTALL_DIR} نصب شد"
}

configure_bot() {
    log_step "پیکربندی ربات"
    
    echo -e "${CYAN}توکن ربات تلگرام:${NC}"
    read -r BOT_TOKEN
    
    echo -e "${CYAN}آیدی عددی ادمین:${NC}"
    read -r ADMIN_ID
    
    echo -e "${CYAN}نام کاربری ربات${NC} (بدون @):"
    read -r BOT_USERNAME
    
    echo -e "${CYAN}دامنه سرور${NC} (مثال: example.com):"
    read -r BOT_DOMAIN
    
    BOT_URL="https://${BOT_DOMAIN}/"
    
    # Create config.php
    cat > "${INSTALL_DIR}/config.php" << PHPEOF
<?php
// MahsaBot Configuration - Generated by installer
define('ESI_DB_HOST', 'localhost');
define('ESI_DB_NAME', '${DB_NAME}');
define('ESI_DB_USER', '${DB_USER}');
define('ESI_DB_PASS', '${DB_PASS}');

define('ESI_BOT_TOKEN', '${BOT_TOKEN}');
define('ESI_ADMIN_ID', ${ADMIN_ID});
define('ESI_BOT_USERNAME', '${BOT_USERNAME}');
define('ESI_BOT_URL', '${BOT_URL}');
define('ESI_BOT_DOMAIN', '${BOT_DOMAIN}');

date_default_timezone_set('Asia/Tehran');
define('ESI_DEBUG', false);
PHPEOF

    log_info "فایل config.php ایجاد شد"
}

setup_ssl() {
    log_step "دریافت گواهی SSL"
    
    echo -e "آیا می‌خواهید SSL (Let's Encrypt) نصب شود؟ (Y/n)"
    read -r ssl_confirm
    
    if [[ "$ssl_confirm" != "n" && "$ssl_confirm" != "N" ]]; then
        echo -e "${CYAN}ایمیل${NC} (برای Let's Encrypt):"
        read -r LE_EMAIL
        
        certbot --apache -d "$BOT_DOMAIN" --non-interactive --agree-tos -m "$LE_EMAIL" 2>/dev/null && {
            log_info "گواهی SSL با موفقیت نصب شد"
        } || {
            log_warn "نصب SSL ناموفق بود. می‌توانید بعداً دستی نصب کنید."
        }
    fi
}

configure_apache() {
    log_step "پیکربندی Apache"
    
    cat > /etc/apache2/sites-available/mahsabot.conf << APEOF
<VirtualHost *:80>
    ServerName ${BOT_DOMAIN}
    DocumentRoot ${INSTALL_DIR}
    
    <Directory ${INSTALL_DIR}>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    
    # Deny access to sensitive files
    <FilesMatch "\.(php|sh|sql)$">
        <If "%{REQUEST_URI} !~ m#^/(bot\.php|gateway/|services/subscription\.php|web/)#">
            Require all denied
        </If>
    </FilesMatch>
    
    ErrorLog \${APACHE_LOG_DIR}/mahsabot_error.log
    CustomLog \${APACHE_LOG_DIR}/mahsabot_access.log combined
</VirtualHost>
APEOF

    a2ensite mahsabot.conf > /dev/null 2>&1
    a2enmod rewrite > /dev/null 2>&1
    systemctl reload apache2
    log_info "Apache پیکربندی شد"
}

create_database_tables() {
    log_step "ساخت جداول دیتابیس"
    
    php "${INSTALL_DIR}/setup/schema.php" && {
        log_info "جداول دیتابیس ایجاد شد"
    } || {
        log_warn "ساخت جداول از طریق PHP ناموفق. تلاش مجدد..."
        # Run inline
        php -r "
        require_once '${INSTALL_DIR}/config.php';
        require_once '${INSTALL_DIR}/core/database.php';
        require_once '${INSTALL_DIR}/setup/schema.php';
        \$db = new mysqli(ESI_DB_HOST, ESI_DB_USER, ESI_DB_PASS, ESI_DB_NAME);
        \$db->set_charset('utf8mb4');
        esi_create_schema(\$db);
        esi_seed_defaults(\$db);
        echo 'OK';
        "
        log_info "جداول دیتابیس ایجاد شد"
    }
}

set_webhook() {
    log_step "تنظیم Webhook"
    
    WEBHOOK_URL="${BOT_URL}bot.php"
    RESULT=$(curl -s "https://api.telegram.org/bot${BOT_TOKEN}/setWebhook?url=${WEBHOOK_URL}")
    
    if echo "$RESULT" | grep -q '"ok":true'; then
        log_info "Webhook تنظیم شد: ${WEBHOOK_URL}"
    else
        log_error "تنظیم Webhook ناموفق: ${RESULT}"
    fi
}

setup_cron_jobs() {
    log_step "تنظیم Cron Jobs"
    
    CRON_FILE="/etc/cron.d/mahsabot"
    cat > "$CRON_FILE" << CRONEOF
# MahsaBot Cron Jobs
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Broadcast messages (every minute)
* * * * * www-data php ${INSTALL_DIR}/services/broadcaster.php >> /var/log/mahsabot_cron.log 2>&1

# Verify TRX payments (every 2 minutes)
*/2 * * * * www-data php ${INSTALL_DIR}/services/tron_verifier.php >> /var/log/mahsabot_cron.log 2>&1

# Check expired subscriptions (every 6 hours)
0 */6 * * * www-data php ${INSTALL_DIR}/services/expiry_monitor.php >> /var/log/mahsabot_cron.log 2>&1

# Distribute gifts (every 5 minutes)
*/5 * * * * www-data php ${INSTALL_DIR}/services/gift_distributor.php >> /var/log/mahsabot_cron.log 2>&1

# Daily report (8:00 AM Tehran time)
0 8 * * * www-data php ${INSTALL_DIR}/services/report_sender.php >> /var/log/mahsabot_cron.log 2>&1
CRONEOF

    chmod 644 "$CRON_FILE"
    log_info "Cron Jobs تنظیم شد"
}

copy_lib_files() {
    log_step "کپی کتابخانه‌ها"
    
    mkdir -p "${INSTALL_DIR}/lib/phpqrcode"
    
    # phpqrcode will be included in the repo
    if [[ -f "${INSTALL_DIR}/lib/phpqrcode/phpqrcode.php" ]]; then
        log_info "کتابخانه QR Code موجود است"
    else
        log_warn "کتابخانه phpqrcode یافت نشد. QR Code غیرفعال خواهد بود."
    fi
}

show_summary() {
    echo ""
    echo -e "${GREEN}${BOLD}"
    echo "  ╔══════════════════════════════════════╗"
    echo "  ║     ✅ نصب با موفقیت انجام شد!      ║"
    echo "  ╚══════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
    echo -e "  ${CYAN}📂 مسیر نصب:${NC}   ${INSTALL_DIR}"
    echo -e "  ${CYAN}🌐 آدرس ربات:${NC}  ${BOT_URL}"
    echo -e "  ${CYAN}🗃️  دیتابیس:${NC}    ${DB_NAME}"
    echo -e "  ${CYAN}👤 کاربر DB:${NC}    ${DB_USER}"
    echo ""
    echo -e "  ${YELLOW}⚠️  نکات مهم:${NC}"
    echo "  ├ رمز دیتابیس را در جای امن ذخیره کنید"
    echo "  ├ مطمئن شوید SSL فعال است"
    echo "  ├ فایل config.php را بازبینی کنید"
    echo "  └ ربات را در تلگرام با /start تست کنید"
    echo ""
    echo -e "  ${BLUE}📚 مستندات:${NC} https://github.com/benAliAlizadeh/mahsabot"
    echo ""
}

# ── Uninstall ────────────────────────────────────────────────────
uninstall() {
    print_banner
    echo -e "${RED}${BOLD}⚠️  حذف MahsaBot${NC}"
    echo ""
    echo -e "این عملیات فایل‌ها، دیتابیس و تنظیمات را حذف می‌کند."
    echo -e "آیا مطمئن هستید؟ (y/N)"
    read -r confirm
    
    if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
        rm -rf "$INSTALL_DIR"
        rm -f /etc/cron.d/mahsabot
        rm -f /etc/apache2/sites-available/mahsabot.conf
        a2dissite mahsabot.conf > /dev/null 2>&1
        mysql -e "DROP DATABASE IF EXISTS \`${DB_NAME}\`;" 2>/dev/null
        mysql -e "DROP USER IF EXISTS '${DB_USER}'@'localhost';" 2>/dev/null
        systemctl reload apache2
        log_info "MahsaBot با موفقیت حذف شد"
    else
        log_info "عملیات لغو شد"
    fi
}

# ── Main Menu ────────────────────────────────────────────────────
main() {
    check_root
    check_os
    print_banner
    
    echo -e "  ${BOLD}عملیات مورد نظر را انتخاب کنید:${NC}"
    echo ""
    echo -e "  ${GREEN}1)${NC} نصب کامل MahsaBot"
    echo -e "  ${YELLOW}2)${NC} بروزرسانی فایل‌ها"
    echo -e "  ${RED}3)${NC} حذف MahsaBot"
    echo -e "  ${BLUE}4)${NC} تنظیم مجدد Webhook"
    echo -e "  ${CYAN}5)${NC} پشتیبان‌گیری از دیتابیس"
    echo -e "  0) خروج"
    echo ""
    echo -ne "  انتخاب شما: "
    read -r choice
    
    case $choice in
        1)
            install_dependencies
            setup_database
            download_bot
            configure_bot
            configure_apache
            setup_ssl
            create_database_tables
            copy_lib_files
            setup_cron_jobs
            set_webhook
            show_summary
            ;;
        2)
            log_step "بروزرسانی"
            cd "$INSTALL_DIR" && git pull 2>/dev/null || log_warn "بروزرسانی از گیت ناموفق"
            chown -R www-data:www-data "$INSTALL_DIR"
            log_info "فایل‌ها بروزرسانی شد"
            ;;
        3)
            uninstall
            ;;
        4)
            if [[ -f "${INSTALL_DIR}/config.php" ]]; then
                BOT_TOKEN=$(php -r "require '${INSTALL_DIR}/config.php'; echo ESI_BOT_TOKEN;")
                BOT_URL=$(php -r "require '${INSTALL_DIR}/config.php'; echo ESI_BOT_URL;")
                set_webhook
            else
                log_error "فایل config.php یافت نشد"
            fi
            ;;
        5)
            BACKUP_FILE="/root/mahsabot_backup_$(date +%Y%m%d_%H%M%S).sql"
            if [[ -f "${INSTALL_DIR}/config.php" ]]; then
                DB_PASS_BACKUP=$(php -r "require '${INSTALL_DIR}/config.php'; echo ESI_DB_PASS;")
                mysqldump -u "$DB_USER" -p"$DB_PASS_BACKUP" "$DB_NAME" > "$BACKUP_FILE"
                log_info "پشتیبان در ${BACKUP_FILE} ذخیره شد"
            else
                log_error "فایل config.php یافت نشد"
            fi
            ;;
        0)
            exit 0
            ;;
        *)
            log_error "انتخاب نامعتبر"
            ;;
    esac
}

main "$@"
